/**
 * Created by hjx on 7/25/2017.
 */
// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'

export const GET_EXAMPLES_REQUEST = 'GET_EXAMPLES_REQUEST'
export const GET_EXAMPLES_SUCCESS = 'GET_EXAMPLES_SUCCESS'
export const GET_EXAMPLES_FAILURE = 'GET_EXAMPLES_FAILURE'

export const GET_NOTICE_REQUEST = 'GET_NOTICE_REQUEST'
export const GET_NOTICE_SUCCESS = 'GET_NOTICE_SUCCESS'
export const GET_NOTICE_FAILURE = 'GET_NOTICE_FAILURE'

export const GET_ADVICE_REQUEST = 'GET_ADVICE_REQUEST'
export const GET_ADVICE_SUCCESS = 'GET_ADVICE_SUCCESS'
export const GET_ADVICE_FAILURE = 'GET_ADVICE_FAILURE'

export const GET_HOT_PRODUCT_REQUEST = 'GET_HOT_PRODUCT_REQUEST'
export const GET_HOT_PRODUCT_SUCCESS = 'GET_HOT_PRODUCT_SUCCESS'
export const GET_HOT_PRODUCT_FAILURE = 'GET_HOT_PRODUCT_FAILURE'

export const GET_OPERATOR_REQUEST = 'GET_OPERATOR_REQUEST'
export const GET_OPERATOR_SUCCESS = 'GET_OPERATOR_SUCCESS'
export const GET_OPERATOR_FAILURE = 'GET_OPERATOR_FAILURE'

export const GET_MAIN_PRODUCT_REQUEST = 'GET_MAIN_PRODUCT_REQUEST'
export const GET_MAIN_PRODUCT_SUCCESS = 'GET_MAIN_PRODUCT_SUCCESS'
export const GET_MAIN_PRODUCT_FAILURE = 'GET_MAIN_PRODUCT_FAILURE'

export const SET_APPRAISAL_REQUEST = 'SET_APPRAISAL_REQUEST'
export const SET_APPRAISAL_SUCCESS = 'SET_APPRAISAL_SUCCESS'
export const SET_APPRAISAL_FAILURE = 'SET_APPRAISAL_FAILURE'
